import type { Component, IacArtifact, SystemModel, TrafficProfile } from "../model/types";
import { PRICING, pickInstance, InstanceFamily } from "../pricing/catalog";
import { sizeTiers, TierSizing } from "../pricing/cost";

const slug = (s: string) => s.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");

function familyForKind(kind: string): InstanceFamily {
  if (kind === "database") return "db";
  if (kind === "cache") return "cache";
  if (kind === "api" || kind === "worker") return "compute";
  return "general";
}

// ---------------- Terraform (AWS) ----------------

function terraformAws(model: SystemModel, sizing: TierSizing[]): string {
  const byId = new Map(model.components.map((c) => [c.id, c]));
  const pricing = PRICING.aws;
  const blocks: string[] = [];
  blocks.push(`# Generated by ScaleScope — starting-point Terraform for AWS.
# Refine networking (VPC/subnets/SGs), IAM and image references before applying.
terraform {
  required_providers {
    aws = { source = "hashicorp/aws", version = "~> 5.0" }
  }
}

provider "aws" {
  region = var.region
}

variable "region" {
  type    = string
  default = "us-east-1"
}`);

  for (const s of sizing) {
    const c = byId.get(s.componentId)!;
    const name = slug(c.id);
    if (c.kind === "external") continue;
    if (c.kind === "load_balancer") {
      blocks.push(`resource "aws_lb" "${name}" {
  name               = "${name}"
  load_balancer_type = "application"
  # attach subnets & security groups
}`);
      continue;
    }
    if (c.kind === "database") {
      const inst = pickInstance(pricing, "db", s.perInstanceVcpu, s.perInstanceMemGb);
      blocks.push(`resource "aws_db_instance" "${name}" {
  identifier            = "${name}"
  engine                = "postgres"
  instance_class        = "${inst.name}"
  allocated_storage     = 100
  multi_az              = ${c.replicated ? "true" : "false"}  # HA standby
  backup_retention_period = 7
  storage_encrypted     = true
  # set username/password via secrets manager
}`);
      continue;
    }
    if (c.kind === "cache") {
      const inst = pickInstance(pricing, "cache", s.perInstanceVcpu, s.perInstanceMemGb);
      blocks.push(`resource "aws_elasticache_cluster" "${name}" {
  cluster_id           = "${name}"
  engine               = "redis"
  node_type            = "${inst.name}"
  num_cache_nodes      = ${Math.max(1, s.instances)}
}`);
      continue;
    }
    // stateless tiers -> launch template + autoscaling group
    const inst = pickInstance(pricing, familyForKind(c.kind), s.perInstanceVcpu, s.perInstanceMemGb);
    blocks.push(`resource "aws_launch_template" "${name}" {
  name_prefix   = "${name}-"
  instance_type = "${inst.name}"
  # image_id = data.aws_ami.app.id
}

resource "aws_autoscaling_group" "${name}" {
  name                = "${name}"
  desired_capacity    = ${s.instances}
  min_size            = ${Math.max(2, Math.ceil(s.instances / 2))}
  max_size            = ${Math.max(s.instances * 2, 4)}
  health_check_type   = "ELB"
  launch_template {
    id      = aws_launch_template.${name}.id
    version = "$latest"
  }
  # target_group_arns / vpc_zone_identifier
}`);
  }

  return blocks.join("\n\n");
}

// ---------------- Kubernetes ----------------

function kubernetes(model: SystemModel, sizing: TierSizing[]): string {
  const byId = new Map(model.components.map((c) => [c.id, c]));
  const docs: string[] = [];
  for (const s of sizing) {
    const c = byId.get(s.componentId)!;
    if (c.kind === "external" || c.kind === "load_balancer") continue;
    const name = slug(c.id);
    const cpuReq = Math.max(100, Math.round(s.perInstanceVcpu * 1000 * 0.6)); // millicores
    const cpuLim = s.perInstanceVcpu * 1000;
    const memReq = Math.max(128, Math.round(s.perInstanceMemGb * 1024 * 0.7));
    const memLim = Math.round(s.perInstanceMemGb * 1024);
    const stateful = c.stateful;
    const kind = stateful ? "StatefulSet" : "Deployment";

    docs.push(`apiVersion: apps/v1
kind: ${kind}
metadata:
  name: ${name}
  labels: { app: ${name} }
spec:
  replicas: ${s.instances}${stateful ? `\n  serviceName: ${name}` : ""}
  selector:
    matchLabels: { app: ${name} }
  template:
    metadata:
      labels: { app: ${name} }
    spec:
      containers:
        - name: ${name}
          image: ${name}:latest
          resources:
            requests: { cpu: "${cpuReq}m", memory: "${memReq}Mi" }
            limits: { cpu: "${cpuLim}m", memory: "${memLim}Mi" }
---
apiVersion: v1
kind: Service
metadata:
  name: ${name}
spec:
  selector: { app: ${name} }
  ports:
    - port: 80
      targetPort: 8080`);

    if (!stateful) {
      docs.push(`apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ${name}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ${name}
  minReplicas: ${Math.max(2, Math.ceil(s.instances / 2))}
  maxReplicas: ${Math.max(s.instances * 2, 4)}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target: { type: Utilization, averageUtilization: 65 }`);
    }
  }
  return docs.join("\n---\n");
}

// ---------------- docker-compose ----------------

function compose(model: SystemModel, sizing: TierSizing[]): string {
  const byId = new Map(model.components.map((c) => [c.id, c]));
  const lines: string[] = ["# Generated by ScaleScope — local/dev topology", "services:"];
  const imageFor = (c: Component) => {
    switch (c.kind) {
      case "database":
        return "postgres:16";
      case "cache":
        return "redis:7";
      case "queue":
        return "rabbitmq:3-management";
      case "search":
        return "opensearchproject/opensearch:2";
      case "load_balancer":
        return "nginx:stable";
      default:
        return `${slug(c.id)}:latest`;
    }
  };
  for (const s of sizing) {
    const c = byId.get(s.componentId)!;
    if (c.kind === "external") continue;
    const name = slug(c.id);
    const replicas = Math.min(s.instances, 3); // keep local sane
    lines.push(`  ${name}:`);
    lines.push(`    image: ${imageFor(c)}`);
    if (c.dependsOn.length) {
      lines.push(`    depends_on: [${c.dependsOn.map(slug).join(", ")}]`);
    }
    lines.push(`    deploy:`);
    lines.push(`      replicas: ${replicas}`);
    lines.push(`      resources:`);
    lines.push(`        limits: { cpus: "${s.perInstanceVcpu.toFixed(1)}", memory: ${Math.round(s.perInstanceMemGb * 1024)}M }`);
  }
  return lines.join("\n");
}

/** Generate IaC artifacts (Terraform/AWS, Kubernetes, docker-compose) for the topology. */
export function generateIac(model: SystemModel, traffic: TrafficProfile): IacArtifact[] {
  const peakRps = Math.max(traffic.baselineRps, traffic.peakRps || traffic.baselineRps);
  const sizing = sizeTiers(model, peakRps);
  return [
    { filename: "main.tf", language: "hcl", content: terraformAws(model, sizing), target: "aws" },
    { filename: "k8s.yaml", language: "yaml", content: kubernetes(model, sizing), target: "kubernetes" },
    { filename: "docker-compose.yml", language: "yaml", content: compose(model, sizing), target: "compose" },
  ];
}
